name: Fetch and Save File

on:
  push:
    branches:
      - master
  
  workflow_dispatch:

jobs:
  fetch_and_save_file:
    runs-on: macos-10.15

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy file from system to repository
      run: |
        uname -a
        ls -la /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add SidecarCore
        git commit -m "Add SidecarCore framework" || true
        git push origin master
